name: CI

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      # - name: Run TypeScript compiler
      #   run: yarn type

      - name: Run Lint
        run: yarn lint

      # - name: Run tests
      #   run: yarn test

      - name: Build
        run: yarn build
